'@startuml C4_Elements
'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

@startuml container-diagram
'!include C4_Container.puml
!includeurl https://raw.githubusercontent.com/xuanye/plantuml-style-c4/master/c4_container.puml

'LAYOUT_AS_SKETCH
'LAYOUT_LEFT_RIGHT

Person(consumer1, "User", "Dev/Tester")
Person(consumer2, "Consumer", "Dev/Tester")

System_Boundary(c1, "MockService") {
    Container(web_server, "RestWebServer", "RestApiController.java", "MockMappingService")
    ContainerDb(mockCache, "Cache", "Java", "MockMapping")
    Container(cacheService, "CacheService", "Java","MockMappingCacheService")

    ContainerDb(fileBaseCache, "FileBaseCache", "Standalone Mode", "FileBase Contract & Schema")
    Container(mockServerService, "MockServerService", "Java","MockServerService")

    Container(mockServerController, "MockServerController", "Java", "Control MockServerThread")
    Container(mockServerThread, "MockServerThread", "Java", "MockServerProcessor")

    Container(restClient, "RestClient", "Java", "None Standalone Mode")
}

System_Ext(contractService, "Contract Service")

Rel(consumer1, web_server, "HTTP", "Get MockServer Port")
Rel_Neighbor(consumer2, mockServerThread, "TCP", "Request Msg")

Rel(mockServerController, restClient,"HTTP GET","GetAllContractIndex")
Rel(mockServerController, mockServerThread,"Java","Create new thread")
Rel(mockServerController, mockServerThread,"EventBus","ShutDownMockEvent")
Rel(mockServerThread, mockServerController,"EventBus","NewMockMappingEvent")
Rel(mockServerThread, restClient,"HTTP GET","GetContractsByIndex/getSchemasByIndex")

Rel(restClient, contractService,"HTTP GET","GetAllContractIndex")
Rel(restClient, contractService,"HTTP GET","GetContractsByIndex/getSchemasByIndex")

Rel(mockServerController, cacheService, "Java","Add Mapping")
Rel(mockServerController, mockServerService, "Java","Add Mapping")
Rel(web_server, mockServerService, "Java","Get Util function")

Rel(cacheService, mockCache, "Static","Add Mapping")
Rel(mockCache, cacheService, "Static","Read Mapping")

Rel(web_server, cacheService,"Java","Read Mapping")

Rel(fileBaseCache, fileBaseCache, "Static","Load Contract")
Rel(mockServerService, fileBaseCache, "Static","Read Contract")


@enduml